version: "3"
services:
    sxlxs:
        image: "sxlxs:dev"
        build:
            context: .
            dockerfile: Dockerfile
        hostname: sxlxs
        stdin_open: true
        tty: true
        working_dir: '/sxlxs-dev'
        volumes:
            - ".:/sxlxs-dev"
